project_id = "gnqqktmslswgjtvxfvdo"

[functions.create-checkout]
verify_jwt = false

[functions.billing]
verify_jwt = false

[functions.voice]
verify_jwt = false

[functions.crawl-ingest]
verify_jwt = false
