project_id = "gnqqktmslswgjtvxfvdo"

[functions.create-checkout]
verify_jwt = false

[functions.billing]
verify_jwt = false

[functions.voice]
verify_jwt = false

[functions.crawl-ingest]
verify_jwt = false

[functions.twilio-router]
verify_jwt = false

[functions.twilio-voice-stream]
verify_jwt = false

[functions.twilio-sms-incoming]
verify_jwt = false

[functions.twilio-status]
verify_jwt = false

[functions.twilio-voice-simple]
verify_jwt = false

[functions.twilio-voicemail]
verify_jwt = false
