// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnqqktmslswgjtvxfvdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducXFrdG1zbHN3Z2p0dnhmdmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDM2OTksImV4cCI6MjA3MDQxOTY5OX0.dSFdbwf_fT4HQYrMG9qtvInmy5VWrWHamZXfxVmUlBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});